name = "site-webradio-sinais-dos-tempos"
main = "server/worker/index.ts"
compatibility_date = "2026-09-12"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_NAME = "Sinais dos Tempos Web Rádio"
GOOGLE_CLIENT_ID = "726821051219-rb7lu89uqfkqc74p0kn0c0mgdqfv7eqt.apps.googleusercontent.com"

[[d1_databases]]
binding = "DB"
database_name = "sinais-dos-tempos-db"
database_id = "88b76b47-e10b-4cd6-8e07-0883330b0e20"
migrations_dir = "cloudflare/migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "sinais-dos-tempos-media"

[observability]
enabled = true

[assets]
directory = "./dist/public"
binding = "ASSETS"
