import { useEffect, useState } from 'react';
import { Eye, EyeOff, GripVertical, LayoutTemplate, Plus, Save, Trash2, Type, X } from 'lucide-react';
import { Link } from 'wouter';
import { useMutation, useQuery } from '@tanstack/react-query';
import { apiFetch } from '@/lib/api';
import { useAuth } from '@/_core/hooks/useAuth';

type Block = { id: string; type: string; label: string; title: string; body: string; visible: boolean };
const defaults: Block[] = [
  { id: 'hero', type: 'hero', label: 'Capa principal', title: 'Mensagem que transforma vidas.', body: 'Imagem, título, chamada e botões da primeira tela.', visible: true },
  { id: 'radio', type: 'radio', label: 'Rádio ao vivo', title: 'Uma programação para acompanhar você', body: 'Cartão de transmissão online.', visible: true },
  { id: 'blog', type: 'blog', label: 'Matérias', title: 'Palavras para o caminho', body: 'Grade com as últimas matérias publicadas.', visible: true },
  { id: 'testimonials', type: 'testimonials', label: 'Testemunhos', title: 'Palavras que renovam a esperança.', body: 'Depoimentos aprovados dos ouvintes.', visible: true },
  { id: 'mission', type: 'mission', label: 'Nossa missão', title: 'Conteúdo que aponta para o alto.', body: 'Texto institucional e chamada final.', visible: true },
];
export default function HomeBuilder(){
  const {isAuthenticated,loading}=useAuth(); const [blocks,setBlocks]=useState<Block[]>(defaults); const [drag,setDrag]=useState<string|null>(null); const [editing,setEditing]=useState<Block|null>(null); const [saved,setSaved]=useState(false);
  const content=useQuery<any[]>({queryKey:['admin-site-content'],queryFn:()=>apiFetch('/api/site-content/admin/all'),enabled:isAuthenticated});
  useEffect(()=>{const raw=content.data?.find((x:any)=>x.contentKey==='home_blocks')?.contentValue;if(raw){try{const parsed=JSON.parse(raw);if(Array.isArray(parsed))setBlocks(parsed)}catch{}}},[content.data]);
  const save=useMutation({mutationFn:()=>apiFetch('/api/site-content',{method:'PUT',body:JSON.stringify({home_blocks:JSON.stringify(blocks)})}),onSuccess:()=>{setSaved(true);setTimeout(()=>setSaved(false),2500)}});
  if(loading)return <main className="container page-main"><div className="loading-state">Verificando acesso...</div></main>;
  if(!isAuthenticated)return <main className="container page-main"><div className="locked-card"><LayoutTemplate size={36}/><h1>Editor visual</h1><p>Entre para alterar a estrutura da página inicial.</p><Link href="/admin/login" className="primary-button">Entrar</Link></div></main>;
  const move=(target:string)=>{if(!drag||drag===target)return;const next=[...blocks];const from=next.findIndex(b=>b.id===drag);const to=next.findIndex(b=>b.id===target);const [item]=next.splice(from,1);next.splice(to,0,item);setBlocks(next);setDrag(null)};
  const add=()=>setEditing({id:`custom-${Date.now()}`,type:'custom',label:'Nova seção',title:'Nova seção',body:'Escreva o conteúdo desta seção.',visible:true});
  const commit=(block:Block)=>{setBlocks(prev=>prev.some(b=>b.id===block.id)?prev.map(b=>b.id===block.id?block:b):[...prev,block]);setEditing(null)};
  return <main className="container admin-main"><div className="admin-header"><div><span className="section-kicker">EDITOR VISUAL</span><h1>Estrutura da página inicial</h1><p>Arraste os blocos para mudar a ordem, oculte seções ou edite seus textos.</p></div><Link href="/admin" className="text-link">Voltar ao painel</Link></div><div className="editor-layout"><section className="editor-card"><div className="ai-title"><LayoutTemplate size={22}/><div><strong>Blocos da home</strong><small>Arraste pelo ícone para reorganizar</small></div></div>{blocks.map(block=><div key={block.id} draggable onDragStart={()=>setDrag(block.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>move(block.id)} className="testimonial-admin-item" style={{cursor:'grab',opacity:block.visible?1:.5}}><GripVertical size={18}/><div style={{flex:1}}><strong>{block.label}</strong><small>{block.title}</small></div><button type="button" title={block.visible?'Ocultar':'Mostrar'} onClick={()=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,visible:!b.visible}:b))}>{block.visible?<Eye size={16}/>:<EyeOff size={16}/>}</button><button type="button" title="Editar" onClick={()=>setEditing(block)}><Type size={16}/></button>{block.type==='custom'&&<button type="button" title="Excluir" onClick={()=>setBlocks(prev=>prev.filter(b=>b.id!==block.id))}><Trash2 size={16}/></button>}</div>)}<button className="ghost-button" type="button" onClick={add}><Plus size={16}/> Adicionar bloco</button><div className="editor-actions"><span className="save-status">{saved?'Estrutura salva e publicada.':'A home usará esta estrutura após salvar.'}</span><button className="primary-button" onClick={()=>save.mutate()} disabled={save.isPending}><Save size={16}/> {save.isPending?'Salvando...':'Salvar estrutura'}</button></div></section><aside className="ai-card"><div className="ai-title"><div><strong>Como no Wix</strong><small>Controle a estrutura sem editar código.</small></div></div><p>Use o ícone de arrastar para mudar a ordem. O olho oculta uma seção e o botão de texto abre a edição do título e da descrição do bloco.</p></aside></div>{editing&&<div className="editor-card" style={{marginTop:24}}><div className="ai-title"><strong>Editar bloco</strong><button type="button" onClick={()=>setEditing(null)}><X size={16}/></button></div><label>Nome da seção<input value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})}/></label><label>Título<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Descrição<textarea value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><div className="editor-actions"><button className="ghost-button" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary-button" onClick={()=>commit(editing)}>Aplicar alterações</button></div></div>}</main>;
}
