import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, Headphones, MessageSquareQuote, Send, Sparkles } from 'lucide-react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { apiFetch } from '@/lib/api';
import { useRadio } from '../contexts/RadioContext';

const fallbackPosts=[{slug:'programacao-especial-de-domingo',title:'Programação Especial de Domingo',summary:'Louvores e mensagens inspiradoras para começar a semana com fé.',category:'Programação'},{slug:'fe-em-tempos-dificeis',title:'Fé em Tempos Difíceis',summary:'Uma reflexão sobre esperança, oração e perseverança.',category:'Reflexão'},{slug:'top-louvores-da-semana',title:'Top Louvores da Semana',summary:'Canções que tocaram corações e renovaram a esperança.',category:'Louvores'}];
export default function Home(){const {data}=useQuery({queryKey:['posts'],queryFn:()=>apiFetch('/api/posts')});const {data:copy}=useQuery<Record<string,string>>({queryKey:['site-content'],queryFn:()=>apiFetch('/api/site-content')});const {data:testimonialsData}=useQuery<any[]>({queryKey:['testimonials'],queryFn:()=>apiFetch('/api/testimonials')});const testimonials=testimonialsData||[];const posts=(data&&data.length?data:fallbackPosts).slice(0,3);const text=(key:string,fallback:string)=>copy?.[key]||fallback;const {playing,toggleAudio}=useRadio();const [form,setForm]=useState({name:'',location:'',content:'',website:''});const [sent,setSent]=useState(false);const [error,setError]=useState('');const submit=useMutation({mutationFn:()=>apiFetch('/api/testimonials/submit',{method:'POST',body:JSON.stringify(form)}),onSuccess:()=>{setForm({name:'',location:'',content:'',website:''});setSent(true);setError('')}});const send=async(e:React.FormEvent)=>{e.preventDefault();setSent(false);setError('');try{await submit.mutateAsync()}catch(err:any){setError(err.message||'Não foi possível enviar seu testemunho.')}};return <main>
  <section className="hero-section"><div className="hero-image"><img src="/images/hero.jpeg" alt="Jesus entre nuvens douradas"/><div className="hero-glow"/></div><div className="container hero-content"><div className="eyebrow"><Sparkles size={15}/> {text('hero_eyebrow','UMA VOZ DE ESPERANÇA')}</div><h1>{text('hero_title_line','Mensagem que')}<br/><em>{text('hero_title_accent','transforma vidas.')}</em></h1><p>{text('hero_description','Ouça, leia e compartilhe conteúdo que aproxima o coração de Deus. A Web Rádio Sinais dos Tempos está com você.')}</p><div className="hero-actions"><button onClick={toggleAudio} className="primary-button"><Headphones size={18}/> {playing?'Pausar rádio':'Ouça ao vivo'}</button><Link href="/blog" className="ghost-button">Explorar o blog <ArrowRight size={17}/></Link></div></div></section>
  <section id="ouvir" className="radio-card-wrap"><div className="container"><div className="radio-card"><div className="radio-card-icon"><Headphones size={25}/></div><div><span className="section-kicker">TRANSMISSÃO ONLINE</span><h2>{text('radio_title','Uma programação para acompanhar você')}</h2><p>{text('radio_description','Pregações, louvores e mensagens proféticas durante todo o dia.')}</p></div><div className="radio-wave" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="radio-note">Aperte <strong>Ouvir ao vivo</strong> no topo da página</div></div></div></section>
  <section className="section container"><div className="section-heading"><div><span className="section-kicker">PALAVRAS PARA O CAMINHO</span></div><Link href="/blog" className="text-link">Ver todas <ArrowRight size={16}/></Link></div><div className="post-grid">{posts.map((post:any,i:number)=><Link href={`/post/${post.slug}`} className={`post-card card-${i}`} key={post.slug}><div className="post-art"><div className="post-art-glow"/><span>{post.category}</span></div><div className="post-card-body"><h3>{post.title}</h3><p>{post.summary}</p><span className="read-more">Ler matéria <ArrowRight size={14}/></span></div></Link>)}</div></section>
  {testimonials.length>0&&<section className="testimonials-section"><div className="container"><div className="section-heading"><div><span className="section-kicker">HISTÓRIAS QUE EDIFICAM</span><h2>Palavras que renovam a esperança.</h2></div></div><div className="testimonials-grid">{testimonials.map((item:any)=><article className="testimonial-card" key={item.id}><div className="testimonial-mark">“</div><p>{item.content}</p><div className="testimonial-person">{item.imageUrl&&<img src={item.imageUrl} alt=""/>}<div><strong>{item.name}</strong>{item.location&&<small>{item.location}</small>}</div></div></article>)}</div></div></section>}
  <section className="submit-testimonial-section"><div className="container submit-testimonial-grid"><div><span className="section-kicker">COMPARTILHE SUA HISTÓRIA</span><h2>Seu testemunho pode fortalecer outra vida.</h2><p>Envie sua experiência com Deus. Nossa equipe fará uma breve análise antes de publicar no site.</p></div><form className="editor-card public-testimonial-form" onSubmit={send}><div className="ai-title"><MessageSquareQuote size={22}/><strong>Enviar testemunho</strong></div><input className="honeypot" tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})} aria-hidden="true"/><label>Nome<input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Seu nome"/></label><label>Cidade ou identificação (opcional)<input maxLength={120} value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Ex.: Cascavel - PR"/></label><label>Seu testemunho<textarea required minLength={10} maxLength={1000} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="Conte como Deus falou ao seu coração..."/><small className="field-counter">{form.content.length}/1000</small></label>{error&&<p className="form-error">{error}</p>}{sent&&<p className="form-success">Recebemos seu testemunho. Obrigado por compartilhar; ele será analisado antes da publicação.</p>}<button className="primary-button" disabled={submit.isPending}>{submit.isPending?'Enviando...':<><Send size={16}/> Enviar para análise</>}</button></form></div></section>
  <section className="mission-section"><div className="container mission-grid"><div><span className="section-kicker">{text('mission_kicker','NOSSA MISSÃO')}</span><h2>{text('mission_title','Conteúdo que aponta para o alto.')}</h2></div><p>{text('mission_description','Em cada palavra, canção e transmissão, buscamos levar paz, conhecimento bíblico e a esperança do retorno de Cristo.')}</p><Link href="/blog" className="primary-button">Conheça o projeto <ArrowRight size={17}/></Link></div></section>
</main>}
