import { useRef, useState } from 'react';
import { AudioLines, Music2, Pencil, ShieldCheck, Trash2, Upload, X } from 'lucide-react';
import { Link } from 'wouter';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiFetch, fileToBase64 } from '@/lib/api';
import { useAuth } from '@/_core/hooks/useAuth';

type Song = { id:number; title:string; artist:string; description?:string|null; audioUrl:string; coverUrl?:string|null; active:number };
const empty = { title:'', artist:'', description:'', audioUrl:'', coverUrl:'' };
export default function LouvoresAdmin(){
  const {isAuthenticated,loading}=useAuth(); const client=useQueryClient(); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<number|null>(null); const [error,setError]=useState(''); const audioRef=useRef<HTMLInputElement>(null);
  const songs=useQuery<Song[]>({queryKey:['admin-songs'],queryFn:()=>apiFetch('/api/songs/admin/all'),enabled:isAuthenticated});
  const save=useMutation({mutationFn:()=>apiFetch(editing?`/api/songs/${editing}`:'/api/songs',{method:editing?'PATCH':'POST',body:JSON.stringify(form)}),onSuccess:()=>{setForm(empty);setEditing(null);setError('');client.invalidateQueries({queryKey:['admin-songs']});client.invalidateQueries({queryKey:['songs']})}});
  const uploadAudio=useMutation({mutationFn:(value:any)=>apiFetch<{url:string}>('/api/media/upload',{method:'POST',body:JSON.stringify(value)})});
  const remove=useMutation({mutationFn:(id:number)=>apiFetch(`/api/songs/${id}`,{method:'DELETE'}),onSuccess:()=>{client.invalidateQueries({queryKey:['admin-songs']});client.invalidateQueries({queryKey:['songs']})}});
  if(loading)return <main className="container page-main"><div className="loading-state">Verificando acesso...</div></main>;
  if(!isAuthenticated)return <main className="container page-main"><div className="locked-card"><ShieldCheck size={36}/><h1>Área reservada</h1><p>Somente a administração pode cadastrar louvores.</p><Link href="/admin/login" className="primary-button">Entrar</Link></div></main>;
  const set=(key:keyof typeof empty,value:string)=>setForm(prev=>({...prev,[key]:value}));
  const edit=(s:Song)=>{setEditing(s.id);setForm({title:s.title,artist:s.artist,description:s.description||'',audioUrl:s.audioUrl,coverUrl:s.coverUrl||''});window.scrollTo({top:0,behavior:'smooth'})};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await save.mutateAsync()}catch(e:any){setError(e.message)}};
  const chooseAudio=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('audio/')){setError('Escolha um arquivo de áudio MP3.');return}if(file.size>25*1024*1024){setError('O MP3 deve ter no máximo 25 MB.');return}try{setError('');const stored=await uploadAudio.mutateAsync({fileName:file.name,mimeType:file.type||'audio/mpeg',base64:await fileToBase64(file),kind:'audio'});set('audioUrl',stored.url)}catch(err:any){setError(err.message||'Não foi possível enviar o MP3.')}e.target.value=''};
  return <main className="container admin-main"><div className="admin-header"><div><span className="section-kicker">PAINEL ADMINISTRATIVO</span><h1>Louvores e MP3</h1><p>{editing?'Edite um louvor existente.':'Cadastre músicas para reprodução online.'}</p></div><Link href="/admin" className="text-link">Voltar ao painel</Link></div><div className="testimonials-admin-layout"><form className="editor-card testimonial-form" onSubmit={submit}><div className="ai-title"><Music2 size={22}/><strong>{editing?'Editar louvor':'Novo louvor'}</strong></div><label>Título<input value={form.title} onChange={e=>set('title',e.target.value)} required/></label><label>Artista<input value={form.artist} onChange={e=>set('artist',e.target.value)} required/></label><label>Descrição<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Arquivo MP3<input ref={audioRef} type="file" accept="audio/mpeg,audio/mp3,audio/*" hidden onChange={chooseAudio}/><button type="button" className="builder-secondary-button" onClick={()=>audioRef.current?.click()} disabled={uploadAudio.isPending}><Upload size={16}/>{uploadAudio.isPending?'Enviando MP3...':'Escolher MP3 do computador'}</button>{form.audioUrl&&<small className="image-name">Arquivo pronto para publicação: {form.audioUrl.split('/').pop()}</small>}</label><label>URL do MP3<input type="text" value={form.audioUrl} onChange={e=>set('audioUrl',e.target.value)} placeholder="Escolha um arquivo ou informe uma URL" required/></label><label>URL da capa<input type="url" value={form.coverUrl} onChange={e=>set('coverUrl',e.target.value)} placeholder="https://..."/></label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><button type="button" className="ghost-button" onClick={()=>{setForm(empty);setEditing(null)}}><X size={16}/> Cancelar</button><button className="primary-button" disabled={save.isPending||uploadAudio.isPending}><Upload size={16}/>{save.isPending?'Salvando...':editing?'Salvar alterações':'Publicar louvor'}</button></div></form><aside className="ai-card"><div className="ai-title"><div><strong>Louvores cadastrados</strong><small>Edite ou exclua músicas</small></div></div>{songs.data?.length?songs.data.map(s=><div className="testimonial-admin-item" key={s.id}><div><strong>{s.title}</strong><small>{s.artist} · {s.active?'Ativo':'Inativo'}</small></div><div className="announcement-admin-actions"><button type="button" title="Editar" onClick={()=>edit(s)}><Pencil size={16}/></button><button type="button" title="Excluir" onClick={()=>{if(confirm('Excluir este louvor?'))remove.mutate(s.id)}}><Trash2 size={16}/></button></div></div>):!songs.isLoading&&<p>Nenhum louvor cadastrado.</p>}</aside></div></main>;
}
