import { useEffect, useState } from 'react';
import { Handshake, Pencil, Plus, Save, ShieldCheck, Trash2, X } from 'lucide-react';
import { Link } from 'wouter';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiFetch } from '@/lib/api';
import { useAuth } from '@/_core/hooks/useAuth';

type Sponsor = { id: number; name: string; description: string; logoUrl?: string | null; bannerUrl?: string | null; websiteUrl?: string | null; whatsapp?: string | null; audioUrl?: string | null; active: number };
type Form = Omit<Sponsor, 'id' | 'active'> & { active: boolean };
const empty: Form = { name: '', description: '', logoUrl: '', bannerUrl: '', websiteUrl: '', whatsapp: '', audioUrl: '', active: true };

export default function SponsorsAdmin() {
  const { isAuthenticated, loading } = useAuth(); const client = useQueryClient();
  const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<number | null>(null); const [error, setError] = useState('');
  const sponsors = useQuery<Sponsor[]>({ queryKey: ['admin-sponsors'], queryFn: () => apiFetch('/api/sponsors/admin/all'), enabled: isAuthenticated });
  const refresh = () => { client.invalidateQueries({ queryKey: ['admin-sponsors'] }); client.invalidateQueries({ queryKey: ['sponsors'] }); };
  const save = useMutation({ mutationFn: () => apiFetch(editing ? `/api/sponsors/${editing}` : '/api/sponsors', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, active: form.active }) }), onSuccess: () => { setForm(empty); setEditing(null); setError(''); refresh(); } });
  const remove = useMutation({ mutationFn: (id: number) => apiFetch(`/api/sponsors/${id}`, { method: 'DELETE' }), onSuccess: refresh });
  useEffect(() => { if (save.error) setError((save.error as Error).message); }, [save.error]);
  if (loading) return <main className="container page-main"><div className="loading-state">Verificando acesso...</div></main>;
  if (!isAuthenticated) return <main className="container page-main"><div className="locked-card"><ShieldCheck size={36}/><h1>Área reservada</h1><p>Somente a administração pode editar patrocinadores.</p><Link href="/admin/login" className="primary-button">Entrar</Link></div></main>;
  const set = (key: keyof Form, value: string | boolean) => setForm(prev => ({ ...prev, [key]: value }));
  const edit = (item: Sponsor) => { setEditing(item.id); setForm({ name: item.name, description: item.description, logoUrl: item.logoUrl || '', bannerUrl: item.bannerUrl || '', websiteUrl: item.websiteUrl || '', whatsapp: item.whatsapp || '', audioUrl: item.audioUrl || '', active: Boolean(item.active) }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <main className="container admin-main"><div className="admin-header"><div><span className="section-kicker">PAINEL ADMINISTRATIVO</span><h1>Patrocinadores</h1><p>Controle todo o conteúdo exibido na página de parceiros.</p></div><Link href="/admin" className="text-link">Voltar ao painel</Link></div>
    <div className="testimonials-admin-layout"><form className="editor-card testimonial-form" onSubmit={e => { e.preventDefault(); setError(''); save.mutate(); }}><div className="ai-title"><Handshake size={22}/><div><strong>{editing ? 'Editar patrocinador' : 'Novo patrocinador'}</strong><small>Todos os campos de mídia são opcionais.</small></div></div><label>Nome<input value={form.name} onChange={e=>set('name',e.target.value)} maxLength={160} required/></label><label>Descrição<textarea value={form.description} onChange={e=>set('description',e.target.value)} required/></label><label>URL do logo<input type="url" value={form.logoUrl || ''} onChange={e=>set('logoUrl',e.target.value)} placeholder="https://..."/></label><label>URL do banner<input type="url" value={form.bannerUrl || ''} onChange={e=>set('bannerUrl',e.target.value)} placeholder="https://..."/></label><label>Site<input type="url" value={form.websiteUrl || ''} onChange={e=>set('websiteUrl',e.target.value)} placeholder="https://..."/></label><div className="announcement-fields"><label>WhatsApp<input value={form.whatsapp || ''} onChange={e=>set('whatsapp',e.target.value)} placeholder="5545999999999"/></label><label>URL do áudio<input type="url" value={form.audioUrl || ''} onChange={e=>set('audioUrl',e.target.value)} placeholder="https://...mp3"/></label></div><label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/> Exibir publicamente</label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><button type="button" className="ghost-button" onClick={()=>{setForm(empty);setEditing(null);setError('')}}>{editing?<><X size={16}/> Cancelar</>:<><Plus size={16}/> Limpar</>}</button><button className="primary-button" disabled={save.isPending}>{save.isPending?'Salvando...':<><Save size={16}/> {editing?'Salvar alterações':'Cadastrar patrocinador'}</>}</button></div></form>
      <aside className="ai-card"><div className="ai-title"><div><strong>Patrocinadores cadastrados</strong><small>Ativos e inativos</small></div></div>{sponsors.isLoading&&<p>Carregando...</p>}{sponsors.data?.length ? sponsors.data.map(item=><div className="testimonial-admin-item" key={item.id}><div><strong>{item.name}</strong><small>{item.active?'Ativo':'Inativo'}</small><p>{item.description}</p></div><div className="announcement-admin-actions"><button type="button" title="Editar" onClick={()=>edit(item)}><Pencil size={16}/></button><button type="button" title="Excluir" onClick={()=>{if(confirm('Excluir este patrocinador?')) remove.mutate(item.id)}}><Trash2 size={16}/></button></div></div>):!sponsors.isLoading&&<p>Nenhum patrocinador cadastrado.</p>}</aside></div></main>;
}
