import { useEffect, useState } from 'react';
import { Check, MessageSquareQuote, Pencil, Plus, ShieldCheck, Trash2, X, XCircle } from 'lucide-react';
import { Link } from 'wouter';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiFetch } from '@/lib/api';
import { useAuth } from '@/_core/hooks/useAuth';

type Testimonial = { id: number; name: string; content: string; location?: string | null; imageUrl?: string | null; active: number; displayOrder: number; moderationStatus: 'pending'|'approved'|'rejected'; moderationNote?: string | null };
type FormState = { name: string; content: string; location: string; imageUrl: string; displayOrder: string; active: boolean };
const emptyForm: FormState = { name: '', content: '', location: '', imageUrl: '', displayOrder: '0', active: true };

export default function TestimonialsAdmin() {
  const { isAuthenticated, loading } = useAuth(); const client = useQueryClient();
  const [form, setForm] = useState<FormState>(emptyForm); const [editing, setEditing] = useState<number | null>(null); const [error, setError] = useState(''); const [filter, setFilter] = useState('');
  const testimonials = useQuery<Testimonial[]>({ queryKey: ['admin-testimonials', filter], queryFn: () => apiFetch(`/api/testimonials/admin/all${filter ? `?status=${filter}` : ''}`), enabled: isAuthenticated });
  const refresh = () => { client.invalidateQueries({ queryKey: ['admin-testimonials'] }); client.invalidateQueries({ queryKey: ['testimonials'] }); client.invalidateQueries({ queryKey: ['notifications'] }); };
  const save = useMutation({ mutationFn: () => apiFetch(editing ? `/api/testimonials/${editing}` : '/api/testimonials', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, displayOrder: Number(form.displayOrder), location: form.location || null, imageUrl: form.imageUrl || null }) }), onSuccess: () => { setForm(emptyForm); setEditing(null); setError(''); refresh(); } });
  const moderate = useMutation({ mutationFn: ({ id, status }: { id: number; status: 'approved'|'rejected' }) => apiFetch(`/api/testimonials/${id}/moderate`, { method: 'PATCH', body: JSON.stringify({ moderationStatus: status }) }), onSuccess: refresh });
  const remove = useMutation({ mutationFn: (id: number) => apiFetch(`/api/testimonials/${id}`, { method: 'DELETE' }), onSuccess: refresh });
  useEffect(() => { if (save.error) setError((save.error as Error).message); }, [save.error]);
  if (loading) return <main className="container page-main"><div className="loading-state">Verificando acesso...</div></main>;
  if (!isAuthenticated) return <main className="container page-main"><div className="locked-card"><ShieldCheck size={36}/><h1>Área reservada</h1><p>O painel de testemunhos é exclusivo para a administração.</p><Link href="/admin/login" className="primary-button">Entrar</Link></div></main>;
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); try { await save.mutateAsync(); } catch (err: any) { setError(err.message || 'Não foi possível salvar o testemunho.'); } };
  const edit = (item: Testimonial) => { setEditing(item.id); setForm({ name: item.name, content: item.content, location: item.location || '', imageUrl: item.imageUrl || '', displayOrder: String(item.displayOrder), active: Boolean(item.active) }); setError(''); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const set = (key: keyof FormState, value: string | boolean) => setForm(prev => ({ ...prev, [key]: value }));
  return <main className="container admin-main"><div className="admin-header"><div><span className="section-kicker">PAINEL ADMINISTRATIVO</span><h1>Testemunhos</h1><p>Revise os envios dos ouvintes antes de publicar.</p></div><Link href="/" className="text-link">Ver site público</Link></div>
    <div className="moderation-tabs"><button className={!filter?'active':''} onClick={()=>setFilter('')}>Todos</button><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>Pendentes</button><button className={filter==='approved'?'active':''} onClick={()=>setFilter('approved')}>Publicados</button><button className={filter==='rejected'?'active':''} onClick={()=>setFilter('rejected')}>Rejeitados</button></div>
    <div className="testimonials-admin-layout"><form className="editor-card testimonial-form" onSubmit={submit}><div className="ai-title"><MessageSquareQuote size={22}/><div><strong>{editing ? 'Editar testemunho' : 'Novo testemunho'}</strong><small>Cadastros internos já entram como publicados.</small></div></div><label>Nome<input value={form.name} onChange={e=>set('name',e.target.value)} maxLength={120} required placeholder="Ex.: Maria da Silva"/></label><label>Testemunho<textarea value={form.content} onChange={e=>set('content',e.target.value)} maxLength={1000} required placeholder="Escreva a mensagem recebida..."/><small className="field-counter">{form.content.length}/1000</small></label><div className="announcement-fields"><label>Cidade ou identificação<input value={form.location} onChange={e=>set('location',e.target.value)} maxLength={120} placeholder="Ex.: Cascavel - PR"/></label><label>Ordem<input type="number" min="0" max="9999" value={form.displayOrder} onChange={e=>set('displayOrder',e.target.value)}/></label></div><label>URL da foto (opcional)<input type="url" value={form.imageUrl} onChange={e=>set('imageUrl',e.target.value)} placeholder="https://... ou /api/media/..."/></label><label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/> Publicar na página inicial</label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><button type="button" className="ghost-button" onClick={()=>{setForm(emptyForm);setEditing(null);setError('')}}>{editing?<><X size={16}/> Cancelar</>:<><Plus size={16}/> Limpar</>}</button><button className="primary-button" disabled={save.isPending}>{save.isPending?'Salvando...':<><Check size={16}/> {editing?'Salvar alterações':'Cadastrar testemunho'}</>}</button></div></form>
      <aside className="ai-card"><div className="ai-title"><div><strong>Fila de moderação</strong><small>{filter ? `Exibindo ${filter}` : 'Todos os testemunhos'}</small></div></div>{testimonials.isLoading&&<p>Carregando...</p>}{testimonials.data?.length ? <div className="testimonial-admin-list">{testimonials.data.map(item=><div className="testimonial-admin-item" key={item.id}><div><strong>{item.name}</strong><small><span className={`moderation-badge ${item.moderationStatus}`}>{item.moderationStatus==='pending'?'Pendente':item.moderationStatus==='approved'?'Publicado':'Rejeitado'}</span> · posição {item.displayOrder}{item.location?` · ${item.location}`:''}</small><p>{item.content}</p></div><div className="announcement-admin-actions">{item.moderationStatus==='pending'&&<><button type="button" title="Aprovar" onClick={()=>moderate.mutate({id:item.id,status:'approved'})}><Check size={16}/></button><button type="button" title="Rejeitar" onClick={()=>moderate.mutate({id:item.id,status:'rejected'})}><XCircle size={16}/></button></>}<button type="button" title="Editar" onClick={()=>edit(item)}><Pencil size={16}/></button><button type="button" title="Excluir" onClick={()=>{if(confirm('Excluir este testemunho?')) remove.mutate(item.id)}}><Trash2 size={16}/></button></div></div>)}</div>:!testimonials.isLoading&&<p>Nenhum testemunho nesta fila.</p>}</aside>
    </div></main>;
}
