import { z } from 'zod';
import { COOKIE_NAME } from '@shared/const';
import { getSessionCookieOptions } from './_core/cookies';
import { systemRouter } from './_core/systemRouter';
import { publicProcedure, protectedProcedure, router } from './_core/trpc';
import { getDb, listPublishedPosts, getPostBySlug, listActiveSponsors, listActiveSongs } from './db';
import { posts, sponsors, songs } from '../drizzle/schema';
import { invokeLLM } from './_core/llm';
import { storagePut } from './storage';
const adminProcedure=protectedProcedure.use(({ctx,next})=>{if(ctx.user.role!=='admin')throw new Error('Acesso restrito ao administrador');return next()});
const slugify=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const base64Upload=async(userId:number,fileName:string,mimeType:string,base64:string,folder:string,maxBytes:number)=>{const bytes=Buffer.from(base64,'base64');if(bytes.length>maxBytes)throw new Error(`O arquivo deve ter no máximo ${Math.round(maxBytes/1024/1024)} MB`);const safe=fileName.replace(/[^a-zA-Z0-9._-]/g,'-');return storagePut(`${folder}/${userId}-${Date.now()}-${safe}`,bytes,mimeType)};
export const appRouter=router({
 system:systemRouter,
 auth:router({me:publicProcedure.query(o=>o.ctx.user),logout:publicProcedure.mutation(({ctx})=>{ctx.res.clearCookie(COOKIE_NAME,{...getSessionCookieOptions(ctx.req),maxAge:-1});return{success:true}as const})}),
 media:router({uploadImage:adminProcedure.input(z.object({fileName:z.string().min(1).max(160),mimeType:z.enum(['image/jpeg','image/png','image/webp','image/gif']),base64:z.string().min(20)})).mutation(async({input,ctx})=>{const stored=await base64Upload(ctx.user.id,input.fileName,input.mimeType,input.base64,'posts',8*1024*1024);return{url:stored.url,key:stored.key}}),uploadAudio:adminProcedure.input(z.object({fileName:z.string().min(1).max(180),base64:z.string().min(20)})).mutation(async({input,ctx})=>{if(!/\.mp3$/i.test(input.fileName))throw new Error('Envie somente arquivos MP3');const stored=await base64Upload(ctx.user.id,input.fileName,'audio/mpeg',input.base64,'songs',25*1024*1024);return{url:stored.url,key:stored.key}})}),
 blog:router({list:publicProcedure.query(()=>listPublishedPosts()),bySlug:publicProcedure.input(z.object({slug:z.string()})).query(({input})=>getPostBySlug(input.slug)),create:adminProcedure.input(z.object({title:z.string().min(3),summary:z.string().min(3),content:z.string().min(3),category:z.string().default('Reflexão'),imageUrl:z.string().optional(),status:z.enum(['draft','published']).default('draft')})).mutation(async({input,ctx})=>{const db=await getDb();if(!db)throw new Error('Banco indisponível');const slug=slugify(input.title)+'-'+Date.now().toString(36);await db.insert(posts).values({...input,slug,authorId:ctx.user.id,publishedAt:input.status==='published'?new Date():null});return{slug}})}),
 sponsors:router({list:publicProcedure.query(()=>listActiveSponsors()),create:adminProcedure.input(z.object({name:z.string().min(2),description:z.string().min(3),logoUrl:z.string().optional(),bannerUrl:z.string().optional(),websiteUrl:z.string().optional(),whatsapp:z.string().optional(),audioUrl:z.string().optional()})).mutation(async({input})=>{const db=await getDb();if(!db)throw new Error('Banco indisponível');await db.insert(sponsors).values(input);return{success:true}})}),
 louvores:router({list:publicProcedure.query(()=>listActiveSongs()),create:adminProcedure.input(z.object({title:z.string().min(2),artist:z.string().min(2),description:z.string().optional(),audioUrl:z.string().min(5),coverUrl:z.string().optional()})).mutation(async({input})=>{const db=await getDb();if(!db)throw new Error('Banco indisponível');await db.insert(songs).values(input);return{success:true}})}),
 ai:router({suggest:adminProcedure.input(z.object({title:z.string(),content:z.string(),action:z.enum(['review','title','summary','seo','commercial']).default('review')})).mutation(async({input})=>{const prompt={review:'Corrija ortografia, pontuação e clareza sem alterar o sentido.',title:'Sugira três títulos fortes e respeitosos.',summary:'Crie um resumo de até 280 caracteres.',seo:'Crie uma meta description e cinco tags.',commercial:'Crie uma chamada comercial curta e profissional para patrocinador.'}[input.action];const response=await invokeLLM({model:'gpt-5-mini',messages:[{role:'system',content:'Você é editor do portal cristão Sinais dos Tempos. Escreva em português do Brasil, com tom acolhedor, claro e responsável.'},{role:'user',content:`${prompt}\nTítulo: ${input.title}\nConteúdo: ${input.content}`} ]});return{suggestion:response.choices?.[0]?.message?.content||''}})})
});
export type AppRouter=typeof appRouter;
